In [2]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Downloading psycopg2_binary-2.9.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 979.2 kB/s eta 0:00:0000:01:010m
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.9

In [17]:
import psycopg2
from psycopg2 import sql

In [16]:
import psycopg2

# Dane połączeniowe do bazy danych
db_config = {
    'host': 'localhost', 
    'dbname': 'postgres',
    'user': 'postgres',
    'password': '1234'
}

# Połączenie z bazą danych
conn = psycopg2.connect(**db_config)
cursor = conn.cursor()

# Przykład dodawania wierszy do tabeli 'llmmodels'
try:
    # Dodaj pierwszy wiersz

    cursor.execute(''' 
                    
                    DROP TABLE IF EXISTS llmmodels CASCADE;
                    DROP TABLE IF EXISTS qa_8k CASCADE;
                    DROP TABLE IF EXISTS qa_8k_llmmodels CASCADE;
                    DROP TABLE IF EXISTS qa_cat CASCADE;
                    DROP TABLE IF EXISTS qa_cat_llmmodels CASCADE;
                    DROP TABLE IF EXISTS qa_dialog CASCADE;
                    DROP TABLE IF EXISTS qa_dialog_llmmodels CASCADE;
                    DROP TABLE IF EXISTS qa_code CASCADE;
                    DROP TABLE IF EXISTS qa_code_llmmodels CASCADE;
                    DROP TABLE IF EXISTS qa_sources CASCADE;  
                    DROP TABLE IF EXISTS qa_sources_llmmodels CASCADE;  
                   
                    -- Tworzenie tabeli 'llmmodels'
                    CREATE TABLE llmmodels (
                        id SERIAL PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        path VARCHAR(255) NOT NULL,
                        prompt_template TEXT,
                        maxtokens INT
                    );
                   
                    -- Tworzenie tabeli 'qa_8k'
                    CREATE TABLE qa_8k (
                        id SERIAL PRIMARY KEY,
                        question TEXT NOT NULL,
                        answer TEXT NOT NULL,
                        domian varchar(255)
                    );
                     

                
                    -- Tworzenie tabeli 'qa_8k_llmmodels' z kluczami obcymi odnoszącymi się do 'qa-8k' i 'llmmodels'
                    CREATE TABLE qa_8k_llmmodels (
                        id SERIAL PRIMARY KEY,
                        qa_8k_id INT NOT NULL,
                        llmmodels_id INT NOT NULL,
                        language VARCHAR(255) NOT NULL,
                        similarity FLOAT NOT NULL,
                        answerLLM TEXT,
                        FOREIGN KEY (qa_8k_id) REFERENCES qa_8k(id),
                        FOREIGN KEY (llmmodels_id) REFERENCES llmmodels(id)
                    );                   
                   
                    -- Tworzenie tabeli 'qa-cat'
                    CREATE TABLE qa_cat (
                        id SERIAL PRIMARY KEY,
                        category VARCHAR(255) NOT NULL,
                        question TEXT NOT NULL,
                        answer TEXT NOT NULL
                    );
                    -- Tworzenie tabeli 'qa_cat_llmmodels' z kluczami obcymi odnoszącymi się do 'qa_cat' i 'llmmodels'
                        CREATE TABLE qa_cat_llmmodels (
                        id SERIAL PRIMARY KEY,
                        qa_cat_id INT NOT NULL,
                        llmmodels_id INT NOT NULL,
                        language VARCHAR(255) NOT NULL,
                        answerLLM TEXT,
                        FOREIGN KEY (qa_cat_id) REFERENCES qa_cat(id),
                        FOREIGN KEY (llmmodels_id) REFERENCES llmmodels(id)
                    );     
                    --Tworznei tabli 'qa-dialog'
                       CREATE TABLE qa_dialog (
                            id SERIAL PRIMARY KEY,
                            q1 TEXT NOT NULL,
                            q2 TEXT NOT NULL,
                            q3 TEXT NOT NULL,
                            q4 TEXT NOT NULL,         
                            a1 TEXT NOT NULL,
                            a2 TEXT NOT NULL,
                            a3 TEXT NOT NULL,   
                            a4 TEXT NOT NULL
                        );      
                    --Tworzenie tabeli 'qa-dialog_llmmodels' z kluczami obcymi odnoszącymi się do 'qa_dialog' i 'llmmodels'
                        CREATE TABLE qa_dialog_llmmodels (
                        id SERIAL PRIMARY KEY,
                        qa_dialog_id INT NOT NULL,
                        llmmodels_id INT NOT NULL,
                        language VARCHAR(255) NOT NULL,
                        aLLM1 TEXT NOT NULL,
                        aLLM2 TEXT NOT NULL,
                        aLLM3 TEXT NOT NULL,
                        aLLM4 TEXT NOT NULL,
                        FOREIGN KEY (qa_dialog_id) REFERENCES qa_dialog(id),
                        FOREIGN KEY (llmmodels_id) REFERENCES llmmodels(id)    
                    );
                    --Tworzenie tabeli 'qa_code'
                        CREATE TABLE qa_code (
                            id SERIAL PRIMARY KEY,
                            question TEXT NOT NULL,
                            answer TEXT NOT NULL
                        );
                    --Tworzenie tabeli 'qa_code_llmmodels' z kluczami obcymi odnoszącymi się do 'qa_code' i 'llmmodels'
                        CREATE TABLE qa_code_llmmodels (
                        id SERIAL PRIMARY KEY,
                        qa_code_id INT NOT NULL,
                        llmmodels_id INT NOT NULL,
                        language VARCHAR(255) NOT NULL,
                        answerLLM TEXT NOT NULL,
                        FOREIGN KEY (qa_code_id) REFERENCES qa_code(id),
                        FOREIGN KEY (llmmodels_id) REFERENCES llmmodels(id)
                    );  
                    --Tworzenie ta beli 'qa-sources
                        CREATE TABLE qa_sources (  
                            id SERIAL PRIMARY KEY,
                            question TEXT NOT NULL,
                            answer TEXT NOT NULL
                        );
                    --Tworzenie tabeli 'qa-sources_llmmodels' z kluczami obcymi odnoszącymi się do 'qa_sources' i 'llmmodels'   
                        CREATE TABLE qa_sources_llmmodels (
                        id SERIAL PRIMARY KEY,
                        qa_sources_id INT NOT NULL,
                        llmmodels_id INT NOT NULL,  
                        language VARCHAR(255) NOT NULL,
                        answerLLM TEXT NOT NULL,
                        FOREIGN KEY (qa_sources_id) REFERENCES qa_sources(id),
                        FOREIGN KEY (llmmodels_id) REFERENCES llmmodels(id)
                    );  
                   '''


)
   
    conn.commit()

    print("Dodano wiersze do tabeli 'llmmodels'.")

except psycopg2.Error as e:
    print("Wystąpił błąd podczas dodawania wierszy:", e)
    conn.rollback()
finally:
    cursor.close()
    conn.close()

Dodano wiersze do tabeli 'llmmodels'.

In [20]:

conn = psycopg2.connect(**db_config)
cursor = conn.cursor()
# Przykład dodawania wierszy do tabeli 'llmmodels'
try:
    # Dodaj pierwszy wiersz

    cursor.execute(''' 
                        INSERT INTO llmmodels (name, path, prompt_template, maxtokens)
                        VALUES
                            ('Model 1', '/path/to/model1', 'Template 1', 100),
                            ('Model 2', '/path/to/model2', 'Template 2', 150);
                        INSERT INTO qa_8k (question, answer)
                        VALUES
                            ('Pytanie 1', 'Odpowiedź 1'),
                            ('Pytanie 2', 'Odpowiedź 2');

                        INSERT INTO qa_8k_llmmodels (qa_8k_id, llmmodels_id, language, similarity, answerLLM)
                        VALUES
                            (1, 1, 'PL', 0.95, 'Odpowiedź LLM 1'),
                            (2, 2, 'PL', 0.90, 'Odpowiedź LLM 2');

                                        INSERT INTO qa_cat (category, question, answer)
                        VALUES
                            ('Kategoria 1', 'Pytanie 1', 'Odpowiedź 1'),
                            ('Kategoria 2', 'Pytanie 2', 'Odpowiedź 2');

                        INSERT INTO qa_cat_llmmodels (qa_cat_id, llmmodels_id, language, answerLLM)
                        VALUES
                            (1, 1, 'PL', 'Odpowiedź LLM 1'),
                            (2, 2, 'PL', 'Odpowiedź LLM 2');

                        INSERT INTO qa_dialog (q1, q2, q3, q4, a1, a2, a3, a4)
                        VALUES
                            ('Pytanie 1', 'Pytanie 2', 'Pytanie 3', 'Pytanie 4', 'Odpowiedź 1', 'Odpowiedź 2', 'Odpowiedź 3', 'Odpowiedź 4'),
                            ('Pytanie 5', 'Pytanie 6', 'Pytanie 7', 'Pytanie 8', 'Odpowiedź 5', 'Odpowiedź 6', 'Odpowiedź 7', 'Odpowiedź 8');
                        INSERT INTO qa_dialog_llmmodels (qa_dialog_id, llmmodels_id, language, aLLM1, aLLM2, aLLM3, aLLM4)
                        VALUES
                            (1, 1, 'PL', 'Odpowiedź LLM 1', 'Odpowiedź LLM 2', 'Odpowiedź LLM 3', 'Odpowiedź LLM 4'),
                            (2, 2, 'PL', 'Odpowiedź LLM 5', 'Odpowiedź LLM 6', 'Odpowiedź LLM 7', 'Odpowiedź LLM 8');
                                    
                                        
                        INSERT INTO qa_code (question, answer)
                        VALUES
                            ('Kod pytanie 1', 'Kod odpowiedź 1'),
                            ('Kod pytanie 2', 'Kod odpowiedź 2');
                                        
                        INSERT INTO qa_code_llmmodels (qa_code_id, llmmodels_id, language, answerLLM)
                        VALUES
                            (1, 1, 'PL', 'Kod odpowiedź LLM 1'),
                            (2, 2, 'PL', 'Kod odpowiedź LLM 2');
                                        
                                        
                        INSERT INTO qa_sources (question, answer)
                        VALUES
                            ('Źródło pytanie 1', 'Źródło odpowiedź 1'),
                            ('Źródło pytanie 2', 'Źródło odpowiedź 2');
                                        
                                        
                        INSERT INTO qa_sources_llmmodels (qa_sources_id, llmmodels_id, language, answerLLM)
                                        
                        VALUES
                            (1, 1, 'PL', 'Źródło odpowiedź LLM 1'),
                            (2, 2, 'PL', 'Źródło odpowiedź LLM 2');





                   '''
    
)
   
    conn.commit()

except psycopg2.Error as e:
    print("Wystąpił błąd podczas dodawania wierszy:", e)
    conn.rollback()
finally:
    if conn:
        cursor.close()
        conn.close()

In [22]:
conn = psycopg2.connect(**db_config)
cursor = conn.cursor()
cursor.execute("SELECT * FROM llmmodels;")
rows = cursor.fetchall()
# Wypisz każdy wiersz
for row in rows:
    print(row)
cursor.execute("SELECT * FROM qa_8k;")
rows = cursor.fetchall()
# Wypisz każdy wiersz
for row in rows:
    print(row)
cursor.execute("SELECT * FROM qa_8k_llmmodels")
rows = cursor.fetchall()
# Wypisz każdy wiersz
for row in rows:
    print(row)
cursor.close()
conn.close()

(1, 'Model 1', '/path/to/model1', 'Template 1', 100)
(2, 'Model 2', '/path/to/model2', 'Template 2', 150)
(3, 'Model 1', '/path/to/model1', 'Template 1', 100)
(4, 'Model 2', '/path/to/model2', 'Template 2', 150)
(1, 'Pytanie 1', 'Odpowiedź 1')
(2, 'Pytanie 2', 'Odpowiedź 2')
(3, 'Pytanie 1', 'Odpowiedź 1')
(4, 'Pytanie 2', 'Odpowiedź 2')
(1, 1, 1, 'PL', 0.95, 'Odpowiedź LLM 1')
(2, 2, 2, 'PL', 0.9, 'Odpowiedź LLM 2')
(3, 1, 1, 'PL', 0.95, 'Odpowiedź LLM 1')
(4, 2, 2, 'PL', 0.9, 'Odpowiedź LLM 2')

In [24]:
from datasets import load_dataset

dataset = load_dataset("sdadas/gpt-exams")['train']

In [28]:
for row in dataset:
    cursor.execute("INSERT INTO qa_8k (question, answer, domian) VALUES (%s, %s, %s)", (row['question'], row['answer'], row['domain']))